name:                chessTactics
version:             0.1.0.0
github:              "OmegaGreeNya/chessTactics"
license:             BSD3
author:              "GreenCake (Nikolai)"
maintainer:          "megamancake@yandex.ru"
copyright:           "2022 GreenCake (Nikolai)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/OmegaGreeNya/chessTactics#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- aeson
- apecs
- containers
- directory
- filepath
- free
- linear
- hashtables
- sdl2
- sdl2-image
- text

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-uni-patterns

library:
  source-dirs: src

executables:
  chessTactics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chessTactics

tests:
  chessTactics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chessTactics
